name: Build zapret-openwrt (kirkwood)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TARGET: kirkwood
      SUBTARGET: generic
      OPENWRT_VERSION: 24.10.2
      SDK_FILE: openwrt-sdk-24.10.2-kirkwood-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
      OPENWRT_SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/kirkwood/generic/openwrt-sdk-24.10.2-kirkwood-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
      PACKAGE_NAME: zapret

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Install host prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential gawk unzip file gettext libncurses5-dev zlib1g-dev \
            libssl-dev python3 rsync tar bzip2 xz-utils zstd ca-certificates \
            curl git

      - name: Download & unpack OpenWrt SDK
        run: |
          mkdir -p $HOME/openwrt && cd $HOME/openwrt
          curl -L -O "$OPENWRT_SDK_URL"
          tar -I zstd -xf "$SDK_FILE"
          # находим каталог SDK
          SDK_DIR=$(find $HOME/openwrt -maxdepth 1 -type d -name "openwrt-sdk-*")
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: (Optional) Cache dl/
        uses: actions/cache@v4
        with:
          path: ~/.openwrt-dl
          key: dl-${{ env.OPENWRT_VERSION }}

      - name: Link dl/ cache
        run: |
          mkdir -p ~/.openwrt-dl
          ln -sfn ~/.openwrt-dl "$SDK_DIR/dl"

      - name: Copy zapret package into SDK
        run: |
          set -eux
          cp -a ./ $SDK_DIR/package/zapret
          cp -a luci-app-zapret $SDK_DIR/package/

      - name: Generate default .config for SDK
        run: |
          cd "$SDK_DIR"
          make defconfig

      - name: Update and install feeds
        run: |
          cd "$SDK_DIR"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build zapret and luci-app-zapret
        run: |
          set -eux
          cd "$SDK_DIR"
          make package/zapret/compile -j$(nproc) V=sc
          make package/luci-app-zapret/compile -j$(nproc) V=sc
          echo "OUT_BASE=$SDK_DIR/bin/packages" >> $GITHUB_ENV
          find "$SDK_DIR/bin/packages" -maxdepth 3 -name "*.ipk" -print

      - name: Upload zapret IPK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zapret-ipk-arm_xscale
          path: |
            ${{ env.OUT_BASE }}/**/zapret*.ipk
            ${{ env.OUT_BASE }}/**/luci-app-zapret*.ipk
